######################## build ###############################

FROM ubuntu:18.04 as builder
RUN apt-get update && \
    apt-get install -y build-essential git m4 unzip rsync curl libev-dev libgmp-dev pkg-config libhidapi-dev libcap2

ARG net=mainnet
RUN git clone -b $net https://gitlab.com/tezos/tezos.git
WORKDIR tezos

RUN curl -Lo - https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux >/usr/local/bin/opam && \
    chmod a+x /usr/local/bin/opam

ENV OPAMROOTISOK=1
RUN opam init --comp=4.06.1 --disable-sandboxing && \
    opam switch 4.06.1
RUN opam update
RUN make build-deps
RUN eval $(opam config env) && make
RUN strip tezos-*
RUN mkdir /_scripts && mkdir /_bin
RUN cp -a scripts/docker/entrypoint.sh /_bin/ && \
    cp -a scripts/docker/entrypoint.inc.sh /_bin/ && \
    cp scripts/alphanet.sh /_scripts/ && \
    cp scripts/alphanet_version /_scripts/ && \
    cp src/bin_client/bash-completion.sh /_scripts/ && \
    cp active_protocol_versions /_scripts/

######################### final ###############################

FROM ubuntu:18.04 as final

RUN apt-get update && \
    apt-get install -y libev-dev libgmp-dev libhidapi-dev netbase && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /_scripts/* /usr/local/share/tezos/
COPY --from=builder /_bin/* /usr/local/bin/
COPY --from=builder /tezos/tezos-node /usr/local/bin/
COPY --from=builder /tezos/tezos-accuser-* /usr/local/bin/
COPY --from=builder /tezos/tezos-admin-client /usr/local/bin/
COPY --from=builder /tezos/tezos-baker-* /usr/local/bin/
COPY --from=builder /tezos/tezos-client /usr/local/bin/
COPY --from=builder /tezos/tezos-endorser-* /usr/local/bin/
COPY --from=builder /tezos/tezos-node /usr/local/bin/
COPY --from=builder /tezos/tezos-protocol-compiler /usr/local/bin/
COPY --from=builder /tezos/tezos-signer /usr/local/bin/

RUN useradd -ms /bin/bash tezos

RUN mkdir -p /var/run/tezos/node /var/run/tezos/client && \
    chown tezos /var/run/tezos/node /var/run/tezos/client

USER tezos
ENV USER=tezos

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
